apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: treinamento-production
spec:
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: treinamento-production
    spec:
      containers:
      - name: treinamento
        image: gcr.io/builders-treinamento/treinamento:latest
        env:
          - name: spring_profiles_active
            value: production
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080