apiVersion: v1
kind: Service
metadata:
  name: treinamento-svc-deployment
  namespace: develop
  labels:
    app: treinamento-deployment
spec:
  selector:
    app: treinamento-deployment
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
