apiVersion: v1
kind: Service
metadata:
  name: treinamento-svc-homolog
  namespace: homolog
  labels:
    app: treinamento-homolog
spec:
  selector:
    app: treinamento-homolog
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
