apiVersion: v1
kind: Service
metadata:
  name: treinamento-svc-production
  labels:
    app: treinamento-production
spec:
  selector:
    app: treinamento-production
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
